### ISSUE TITLE
Haku UVOs not linked with Chasers in my Food

### ISSUE THREAD

**Issue by sunglassesmichael** [madcowfred/padherder-issues#392]
At least, I assume that this is the reason that she no longer shows up on the My Food page.

I think it applies to Karin, too, since my Karin is not there. Perhaps Leilan and Meimei as well, but I don't have them to check.

**Comment by madcowfred** [comment]
Fixed.

**Comment by sunglassesmichael** [comment]
Thanks!

Blue Chasers still don't show up as food for B/G Karin, though.
