### ISSUE TITLE
Mobile: Filter panel can't be dismissed

### ISSUE THREAD

**Issue by DreadPirateShawn** [madcowfred/padherder-issues#548]
It's impossible to filter monsters on the mobile site -- once the filter panel is expanded, it can't be dismissed.
- Load the monsters tab
- Click the secondary menu drop-down (the one that shows "Add monster", "Filters", "Sorting")
- Click the "Filters" arrow to see all the filter options
- Now you're in the bug repro -- filtering does work, but you can't dismiss the filter panel... the secondary menu drop-down seems to be toggling the initial menu (you can see "Add monster" appear and disappear in the menu bar, I think that's the initial menu appearing behind the filter panel)

Repro confirmed on Firefox (Android) and on Chromium (Mac), the latter achieved by shrinking the window until the mobile site layout is triggered.

I checked the catch-all mobile ticket (#184) but it doesn't appear to include this issue.

**Comment by FaxCelestis** [comment]
Also occurs in Safari on iOS.

**Comment by madcowfred** [comment]
Should be fixed now.

**Comment by xedis** [comment]
Issue is still occuring in Chrome using Ubuntu 15.10

![image](https://cloud.githubusercontent.com/assets/4144634/9292506/1dab8a7a-43b2-11e5-9aa7-6b38e57e76be.png)
