### ISSUE TITLE
Leader skills broken on My Teams page for several leaders

### ISSUE THREAD

**Issue by sionar** [madcowfred/padherder-issues#839]
The leader skills for some of the newer monsters do not work on the My Teams page. For example, the right column for "Total ATK" does not change for #2279 Vigorous Hunt Gods, U&Y. The HP and RCV leader multipliers do not take effect for monsters like the Awoken Norse, Dragonbounds and the new Super-ulti and Awoken Archangels.

**Comment by madcowfred** [comment]
These should be fixed now. Probably.

**Comment by sionar** [comment]
The ones I mentioned are working properly now. Some that are still not working: #2325 Awoken Yomi, #2566 Ultimate Blue Sonia, #2567 Ultimate Green Sonia. There may be more that I didn't notice.

**Comment by madcowfred** [comment]
Leader skills are largely manual and realllly tedious, I tend to just update the ones people ask for. Those 3 are now done.
