### ISSUE TITLE
Some minor missed updates

### ISSUE THREAD

**Issue by IvanWangDev** [madcowfred/padherder-issues#918]
Just the one's I've noticed...

Supergirl orb enhance was replaced by another TPA
Zaerog (#1215) is missing awoken material killer
RCV latents now give 5% instead of 4%
Autoheal latents now give 15% instead of 3%

**Comment by IvanWangDev** [comment]
Masamune and the other weapon series got sub attributes matching their actives.

**Comment by IvanWangDev** [comment]
Bug: Awoken Isis active CD says 2 turns (instead of 3) when you show maxed stats.

**Comment by jgoldshlag** [comment]
Weapon series all should be fixed now

**Comment by Raijinili** [comment]
Are any of these, other than Material Killer, still a problem?

**Comment by ryuujinzero** [comment]
Yes. Vendor killer, enhance killer, and evo mat killer are all missing

**Comment by ryuujinzero** [comment]
Other issues resolved, new issue created for awakening issue. #989
