### ISSUE TITLE
Reincarnated Parvati Evo incorrect in padheader

### ISSUE THREAD

**Issue by pennywaltz** [madcowfred/padherder-issues#961]
So I have a #241 Parvati. I set this Parvati's the evo goal to #3243 Reincarnated Parvati. Padheader's next evo step for my #241 Parvati after setting that evo is #116 White Hot Dancing Goddess, Parvati.

That is not right. Based on the website, http://www.puzzledragonx.com/en/monster.asp?n=3243 it should be #241 Parvati ==> #1956 Awoken Parvati ==> #3243 Reincarnated Parvat

Same thing for Neptune... it thinks it can go from #391 Sea Deity, Abyss Neptune to #3239 Reincarnated Neptune

**Comment by radiantlf** [comment]
I second parvati. The evolution path for bastet is also incorrect.

**Comment by ryuujinzero** [comment]
Most reincarnated and Ace/Ana monsters have issues.

**Comment by ryuujinzero** [comment]
Here is a list of the monsters currently affected by this issue (it is guaranteed to grow)

3271 Reincarnated Hino Kagutsuchi 
3272 Reincarnated Horus 
3238 Reincarnated Minerva 
3241 Reincarnated Shiva 
3242 Reincarnated Lakshmi 
3239 Reincarnated Neptune 
3384 Reincarnated Bastet 
3240 Reincarnated Ceres 
3243 Reincarnated Parvati 
3273 Reincarnated Ra 
3269 Reincarnated Venus 
3385 Reincarnated Anubis 
3270 Reincarnated Hades

**Comment by wmedlar** [comment]
This bug has been fixed and is currently in review.

**Comment by ryuujinzero** [comment]
The bugfix has been deployed and works for all of the Reincarnated evos I've tested so far (Horus, Parvati, Ceres).

**Comment by afeldspar** [comment]
I hate to be the bearer of bad news, but I don't think the fix worked after all.  This is how Lakshmi's evolution tree looks right now, and as you can see, Reincarnated Lakshmi's still showing up as a path from Heavenly Fortune Goddess, Lakshmi.

![image](https://cloud.githubusercontent.com/assets/13708184/26757150/50d8835a-4881-11e7-99ff-f41632d7c8f8.png)

I checked the evolution trees for the monsters listed in the Dec. 17 comment, and some of them seem fixed and some seem still bugged.  I've listed them:

### Bugged
- Horus
- Minerva
- Neptune
- Bastet
- Ceres
- Parvati

### Seems okay

- Hino K.
- Shiva
- Venus
- Ra
- Anubis
- Hades
